---
engines:
  bandit:
    enabled: true
    exclude_paths:
      - 'backend/tests/**'
      - 'backend/alembic/versions/**'
exclude_paths:
  - 'node_modules/**'
  - 'venv/**'
  - '__pycache__/**'
  - '.pytest_cache/**'
  - 'backend/alembic/versions/**'
  - '**/*.egg-info/**'
  - 'dist/**'
  - 'build/**'
  - '.coverage'
  - 'coverage.xml'
  - 'htmlcov/**'
